### ISSUE TITLE
Flitcie menu export broken

### ISSUE THREAD

**Issue by praseodym** [WISVCH/w3cie#1]
The Drupal menu is not exported for use in the Flitcie site; it has not been updated since the Drupal 7 upgrade.

**Comment by praseodym** [comment]
Maybe we should remove the exported menu and replace it e.g. a "Back to CH Website" link. That'll work with other new applications as well (e.g. [connect](https://github.com/WISVCH/connect) and [selfservice](https://github.com/WISVCH/selfservice)).

**Comment by sanderploegsma** [comment]
:+1:

**Comment by praseodym** [comment]
https://github.com/WISVCH/w3cie/blob/d4cb8659f3b8b7e0a74d83386b06842a90d1d3fc/gallery/themes/challenge/views/page.html.php#L95-L97
https://github.com/WISVCH/w3cie/blob/d4cb8659f3b8b7e0a74d83386b06842a90d1d3fc/gallery/modules/challenge_menu/helpers/challenge_menu_theme.php#L10-L25 (also explains why it's not working)
