### ISSUE TITLE
PHP error in page.tpl.php

### ISSUE THREAD

**Issue by praseodym** [WISVCH/w3cie#11]
`Notice: Undefined variable: query in include() (line 114 of /srv/www/drupal7/sites/default/themes/CHallenge/page.tpl.php).`

https://ch.tudelft.nl/en/admin/reports/dblog
https://ch.tudelft.nl/en/admin/reports/event/4936810

**Comment by sanderploegsma** [comment]
Ah toch. Ik twijfelde al of kopieren van internet een goed idee was :sweat:
