### ISSUE TITLE
Error: Undefined variable … in page.tpl.php

### ISSUE THREAD

**Issue by praseodym** [WISVCH/w3cie#16]
``Notice: Undefined variable: query in include() (regel 114 van /srv/www/drupal7/sites/default/themes/CHallenge/page.tpl.php).``
See e.g. https://ch.tudelft.nl/admin/reports/event/4955670

**Comment by praseodym** [comment]
Oh, zelfde als #11 - nog niet live gezet @sanderploegsma ?

**Comment by sanderploegsma** [comment]
Ja zou kunnen...

**Comment by sanderploegsma** [comment]
Had hem idd niet live gezet. Nu wel. :shipit:
