### ISSUE TITLE
Make repository public

### ISSUE THREAD

**Issue by praseodym** [WISVCH/w3cie#6]
Can we make this repository public?

**Comment by praseodym** [comment]
En hij is open source!

**Comment by sanderploegsma** [comment]
Ik weet alleen nog steeds niet in hoeverre de inhoud van deze repo boeiend is voor mensen buiten de W3Cie.

**Comment by praseodym** [comment]
Dat is niet echt een voorwaarde om een project open source te maken, toch?

**Comment by sanderploegsma** [comment]
Fair enough :stuck_out_tongue_winking_eye:
